name: Get Context on PR

on:
  pull_request_target:
    types: [opened]  # This workflow triggers when a pull request is opened.

permissions:
  issues: write

jobs:
  pr_simple_comment:
    runs-on: ubuntu-latest  # Specifies the runner.
    steps:
      - name: Leave a comment on the PR
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const message = "Writing from Actions PR2";
            github.rest.issues.createComment({
              owner: "SuttGHA",
              repo: "my-gha-1",
              issue_number: "6",
              body: message
            });

  # this only gets base repos code, not updated code from pr
  pr_simple_get_code_base:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: list files
        run: |
          ls -R

  # This ref setting allow us to get the code
  # the pr submitter intended to commit
  pr_simple_get_code_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  
          ref: ${{ github.event.pull_request.head.sha }}

      - name: list files
        run: |
          ls -R
  
  
  pr_simple_echo_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: List changed files
        uses: actions/github-script@v6
        id: files
        with:
          script: |
            console.log(JSON.stringify(context.payload.pull_request, null, 2))


  pr_simple_pr_files:
    # This doesnt work
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: List changed files
        uses: actions/github-script@v6
        id: files
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            pr_number = context.payload.number;
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: "SuttGHA",
              repo: "my-gha-1",
              pull_number: pr_number
            });
            console.log('done:');
            cosnole.log(pr_number);
            console.log(pullRequest);
            console.log(pullRequest.files);
            return pullRequest.files;

      - name: Log .md files
        env:
            EXAMPLE_ONE: ${{ steps.files.outputs.result }}
        run: echo "$EXAMPLE_ONE"

  # This only gets a printout of the diff
  pr_simple_diff_url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const diff_url = context.payload.pull_request.diff_url
            const result = await github.request(diff_url)
            console.log(result)

  # These work and are good examples
  pr_simple_changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4

      # -----------------------------------------------------------------------------------------------------------
      # Example 1
      # -----------------------------------------------------------------------------------------------------------
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
        # with:
        #   since_last_remote_commit: true 

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

      # -----------------------------------------------------------------------------------------------------------
      # Example 2
      # -----------------------------------------------------------------------------------------------------------
      - name: Get all changed markdown files
        id: changed-markdown-files
        uses: tj-actions/changed-files@v44
        with:
          # Avoid using single or double quotes for multiline patterns
          files: |
             **.md

      - name: List all changed files markdown files
        if: steps.changed-markdown-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
