name: PR Hello World

on:
  pull_request:
    types: [opened]

jobs:
  make-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Hello PR Step
        run: echo "Hello, PR!"