name: Get Context on PR

on:
  pull_request_target:
    types: [opened]  # This workflow triggers when a pull request is opened.

permissions:
  issues: write

jobs:
  pr_simple_comment:
    runs-on: ubuntu-latest  # Specifies the runner.
    steps:
      - name: Leave a comment on the PR
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const message = "Writing from Actions PR2";
            github.rest.issues.createComment({
              owner: "SuttGHA",
              repo: "my-gha-1",
              issue_number: "6",
              body: message
            });

  pr_simple_get_code:
    runs-on: ubuntu-latest  # Specifies the runner.
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure all history is checked out
  
  pr_simple_echo_1:
    runs-on: ubuntu-latest
    steps:
      - name: List changed files
        uses: actions/github-script@v6
        id: files
        with:
          script: |
            console.log(JSON.stringify(context.payload.pull_request, null, 2))


  pr_simple_pr_files:
    runs-on: ubuntu-latest
    steps:
      - name: List changed files
        uses: actions/github-script@v6
        id: files
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            pr_number = context.payload.number;
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: "SuttGHA",
              repo: "my-gha-1",
              pull_number: pr_number
            });
            console.log('done:');
            cosnole.log(pr_number);
            console.log(pullRequest);
            console.log(pullRequest.files);
            return pullRequest.files;

      - name: Log .md files
        env:
            EXAMPLE_ONE: ${{ steps.files.outputs.result }}
        run: echo "$EXAMPLE_ONE"
  pr_simple_diff_url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const diff_url = context.payload.pull_request.diff_url
            const result = await github.request(diff_url)
            console.log(result)
