name: Write Comment on Push 1

on: [push]  # This workflow triggers on a push event to the repository.

permissions:
  issues: write

jobs:
  new_welcome_message:
    runs-on: ubuntu-latest  # Specifies the runner.

    steps:

      - name: Leave a comment on the Issue6
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const message = "Writing from Actions";
            github.rest.issues.createComment({
              "SuttGHA",
              "my-gha-1",
              6,
              body: message
            });
